/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCategorySlugRouteImport } from './routes/c/$categorySlug'
import { Route as TSlugStyleColorRouteImport } from './routes/t/$slug.$styleColor'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategorySlugRoute = CCategorySlugRouteImport.update({
  id: '/c/$categorySlug',
  path: '/c/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugStyleColorRoute = TSlugStyleColorRouteImport.update({
  id: '/t/$slug/$styleColor',
  path: '/t/$slug/$styleColor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/c/$categorySlug': typeof CCategorySlugRoute
  '/t/$slug/$styleColor': typeof TSlugStyleColorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/c/$categorySlug': typeof CCategorySlugRoute
  '/t/$slug/$styleColor': typeof TSlugStyleColorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/c/$categorySlug': typeof CCategorySlugRoute
  '/t/$slug/$styleColor': typeof TSlugStyleColorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/favorites'
    | '/login'
    | '/sale'
    | '/search'
    | '/c/$categorySlug'
    | '/t/$slug/$styleColor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/favorites'
    | '/login'
    | '/sale'
    | '/search'
    | '/c/$categorySlug'
    | '/t/$slug/$styleColor'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/favorites'
    | '/login'
    | '/sale'
    | '/search'
    | '/c/$categorySlug'
    | '/t/$slug/$styleColor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  SaleRoute: typeof SaleRoute
  SearchRoute: typeof SearchRoute
  CCategorySlugRoute: typeof CCategorySlugRoute
  TSlugStyleColorRoute: typeof TSlugStyleColorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$categorySlug': {
      id: '/c/$categorySlug'
      path: '/c/$categorySlug'
      fullPath: '/c/$categorySlug'
      preLoaderRoute: typeof CCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/$styleColor': {
      id: '/t/$slug/$styleColor'
      path: '/t/$slug/$styleColor'
      fullPath: '/t/$slug/$styleColor'
      preLoaderRoute: typeof TSlugStyleColorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  SaleRoute: SaleRoute,
  SearchRoute: SearchRoute,
  CCategorySlugRoute: CCategorySlugRoute,
  TSlugStyleColorRoute: TSlugStyleColorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
